### PR TITLE
Update to 3.0.1

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by 0xbe7a** [comment]
From the OSX py>39 builds:

```
 error: linking with `x86_64-apple-darwin13.4.0-clang` failed: exit status: 1
    = note: x86_64-apple-darwin13.4: error: unable to execute command: Segmentation fault: 11
            x86_64-apple-darwin13.4: error: linker command failed due to signal (use -v to see invocation)
```

Seems like another case of https://github.com/conda-forge/polars-feedstock/issues/259

**Comment by isuruf** [comment]
Linux build fail with a different error

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
All platforms except windows passes.

On windows, the issue is with unpacking arrow into a folder that already has a long name and with the arrow repo having files that are long, this results in a file with absolute path having more than 255 characters.

Options:
- Unvendor arrow
- Skip windows
- try to download arrow somewhere else.

**Comment by tomjakubowski** [comment]
> On windows, the issue is with unpacking arrow into a folder that already has a long name and with the arrow repo having files that are long, this results in a file with absolute path having more than 255 characters.

Another potential option, we worked around this issue in perspective's CI by placing the build directory at a known short path, `D:\psp-rust`

https://github.com/finos/perspective/blob/master/.github/workflows/build.yaml#L206
https://github.com/finos/perspective/blob/master/.github/workflows/build.yaml#L218C25-L218C36

**Comment by isuruf** [comment]
This is ready

**Pull request merged**
