### PR TITLE
uplift to latest way of melding dash and underscore variants, fixes #82

### LINKED ISSUE #82: Propagate upstream changes
### Comment:

https://github.com/conda-forge/staged-recipes/pull/18964

### PR DESCRIPTION
**Pull request by timkpaine**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by timkpaine** [comment]
@conda-forge/help-python @conda-forge/core could use some guidance here, I have 2 metapackages `perspective-python` and `perspective_python` to match pypa, and I get build failures but only on arm from a dependency `KeyError: Dist(channel='conda-forge', dist_name='bzip2-1.0.8-h3422bc3_4', name='bzip2', fmt='.tar.bz2', version='1.0.8', build_string='h3422bc3_4', build_number=4, base_url=None, platform=None)
`.

**Comment by hmaarrfk** [comment]
I feel like this is the same error as https://github.com/conda-forge/importlib_metadata-feedstock/pull/107

**Comment by timkpaine** [comment]
start here for iteration https://github.com/conda-forge/staged-recipes/pull/18963

**Comment by timkpaine** [comment]
well its even weirder than I expected but I will leave it for now

**Comment by timkpaine** [comment]
moving to https://github.com/conda-forge/perspective-feedstock/pull/94

**Pull request closed without merging**
